### ISSUE TITLE
Add possibility to run Rubocop in parallel mode

### ISSUE THREAD

**Issue by texpert** [vassilevsky/face_control#16]
As of version 0.49, Rubocop could be run parallelized:

```
rubocop --parallel
```

Could you, please, implement this option?

**Comment by vassilevsky** [comment]
Good idea. Thanks, Aurel.

My main concern is the resulting report. Will it still be a single JSON file if RuboCop runs in parallel? Face Control parses the JSON report, so this is important.

Another option might be to add an option to Face Control to not run RuboCop at all, and just read the JSON report. In this case Face Control users will be able to run RuboCop however they like.

We don't actively use Face Control at the moment so we will not be doing this ourselves. However, we'll accept a nice pull request for either of these solutions.

**Comment by texpert** [comment]
It will be a single JSON file, Ilya!

"Files are inspected in parallel, but cops are being run in sequence on a given file." - see https://github.com/rubocop-hq/rubocop/pull/4272

So, I have created a PR for enabling parallel mode - https://github.com/funbox/face_control/pull/21

**Comment by vassilevsky** [comment]
That's nice. Thanks.

**Comment by vassilevsky** [comment]
I thought this was enough of a reason to finally publish **v1.0.0** so I did.
